version: '3.8'

services:
  app:
    build: .  # Build from the Dockerfile in the current directory
    env_file:
      - .env  # Load environment variables from the .env file
    ports:
      - "8000:8000"  # Map port 8000 of the container to port 8000 on the host
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    depends_on:
      - redis  # Ensure Redis service starts before the app

  redis:
    image: redis:latest  # Use the latest Redis image from Docker Hub
    ports:
      - "6379:6379"  # Map port 6379 of the container to port 6379 on the host
